remote_theme: https://github.com/JV-conseil/jekyll-theme-read-the-docs
direction: rtl
title: ترجمه کتاب Hands-On Domain-Driven-Design with .NET Core
description: اقتباسی از کتاب، برای یادگیری و درک DDD
lang: fa

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have plugins defined
  - jekyll-avatar
  - jekyll-mentions